### ISSUE TITLE
Discussion of precedence order in README files is confusing/misleading.

### ISSUE THREAD

**Issue by GrahamDumpleton** [sclorg/s2i-python-container#173]
In the README files for each image where talks about **Run strategies** it says:

> The Docker image produced by s2i-python executes your project in one of the following ways, in precedence order:

It then goes to list the strategies in the order:

* Gunicorn
* Django development server
* Python script

This is a bin confusing/misleading as one could interpret that this means that Gunicorn takes precedence over Django development server over Python script, where as the actual order is Python script via ``app.py``, then ``wsgi.py`` or module installed by ``setup.py`` via Gunicorn and finally ``python manage.py runserver`` if a Django application.

So the order of what takes precedence needs to be better described as current documentation doesn't really explain it succinctly.

For reference, here is what was in the discovery center docs which still haven't see light of day:

* https://github.com/openshift/discoverycenter/blob/master/source/developer/languages/python/advanced-deployment.html.adoc#automatic-detection

**Comment by torsava** [comment]
I'll try to get to this in the coming days.

**Comment by frenzymadness** [comment]
I don't know the history of the readme file but now it seems that run strategies are well explained and each strategy has conditions which have to be met in order to use the strategy.

For example, Gunicorn strategy description says that it'll be used if gunicorn is installed. Django development server strategy also says that it'll be used when Django is in your requirements but you don't have gunicorn. Python script and Application script file also mention some default values.

Maybe we could remove the "precedence order" phrase?
