### ISSUE TITLE
Tests needed for python's virtual environment added in a recent PR

### ISSUE THREAD

**Issue by pkubatrh** [sclorg/s2i-python-container#177]
The use of Python's virtual environment has been added in #159 alas without any tests included. It would be nice to have some at least.

The PR has also added an option to upgrade pip to the latest version.
I have proposed adding a test that would try to install a Python wheel after doing a pip upgrade, however we will be getting pip rebased to version 8.1.2 (https://bugzilla.redhat.com/show_bug.cgi?id=1344674) which should make the default pip able to install wheels without the upgrade so the test would not help with verifying the change.

**Comment by GrahamDumpleton** [comment]
Ignore the test for updating ``pip``, which didn't know how to add with way current test harness work, the use of the virtual environment is tested indirectly by all existing tests that install packages. If there was a significant issue, the existing tests would work. One could add extra checks to validate ``which python`` returns Python from the virtual environment but how do you add it, using ``.s2i/bin`` override scripts, since no concept of action hooks to allow easy insertion of scripts at any step.

**Comment by torsava** [comment]
I've looked into adding the tests for the virtualenv and pip upgrade.

Please take a look: PR #192.

**Comment by torsava** [comment]
Tests were added in PR #192, closing.
