### ISSUE TITLE
RFE: Reduce s2i image size

### ISSUE THREAD

**Issue by fridex** [sclorg/s2i-python-container#242]
The resulting image of an s2i build has 10 layers resulting in nearly 250MiB image for a simple API service (CentOS 7, Python 3.6). It would be nice to reduce image size.

Also squashing image layers would be helpful.

**Comment by omron93** [comment]
Currently centos based images are intentionally not squashed. To see discussion connected to this - see https://github.com/sclorg/rhscl-container-ci/issues/5

**Comment by frenzymadness** [comment]
I tried to squash python-36-centos7 and it reduces image size by only 12 % from 645.55 MB to 567.99 MB.

The newest centos7 base image `s2i-base-centos7` has 479 MB so I am not sure how much we can reduce its size.

Because this might be a problem for more than just Python containers, could we close this issue and discuss it broader in the mentioned issue?

**Comment by fridex** [comment]
> Because this might be a problem for more than just Python containers, could we close this issue and discuss it broader in the mentioned issue?

Yes, thanks for reply!
