### ISSUE TITLE
passing args to APP_FILE

### ISSUE THREAD

**Issue by magick93** [sclorg/s2i-python-container#253]
Hello

When I try to run a python application and specify the `APP_FILE` it seems to work (my application requires parameters to be passed so I cannot say for certain). For example:

```
docker run -e APP_FILE="main.py" my/pgapp 
---> Running application from Python script (main.py) ...
```

However, when I pass parameters - it doesnt work:

```
docker run -e APP_FILE='main.py --mode=dev --algo=1'  my/pgapp
ERROR: file 'main.py --mode=dev --algo=1' not found.
```

**Comment by pkubatrh** [comment]
Yes passing arguments through `APP_FILE` does not work.

To work around the issue you can use `APP_SCRIPT` instead, from which you can run your python application directly with additional arguments.

Ref: https://github.com/sclorg/s2i-python-container/issues/176

**Comment by magick93** [comment]
Thanks, I tried that but it also didnt work.

**Comment by pkubatrh** [comment]
chmod +x dev.sh?

**Comment by GrahamDumpleton** [comment]
You are better off supplying your ``app.sh`` and have it define the custom command with it taking extra arguments from a separate environment variable. Don't use ``APP_FILE`` or ``APP_SCRIPT`` with arguments because ``assemble`` and ``run`` scripts may depend on them being a path only so can be used in tests to see if file exists.

**Comment by frenzymadness** [comment]
Is this still relevant? Did changing permissions solve your problem?
