### ISSUE TITLE
Add support for memcached

### ISSUE THREAD

**Issue by rarguello** [sclorg/s2i-python-container#305]

**Comment by torsava** [comment]
The memcached package itself is only 121K, so very little. If it doesn't need large dependencies (needs to be tested), I'm open to adding it.

If anyone has time to take a look and do a PR, please do.

**Comment by torsava** [comment]
@rarguello I see you've opened a PR #306 for this, but you're adding `libmemcached-devel` instead of `memcached`. `memcached` makes sense to me, as your application might want to use it to cache. However why do you need `libmemcached-devel`? That seems like a package for developing caching servers themselves, which doesn't seem suited for the s2i-python-container.

**Comment by frenzymadness** [comment]
This issue is more than two months without reply so I am closing it. Feel free to reopen it if you still need any help from us.
