### ISSUE TITLE
Package latest release and/or update README to show correct image names

### ISSUE THREAD

**Issue by jtratner** [sclorg/s2i-python-container#323]
I'd like to use the `pipenv` support from this repo; however, I've been unable to find the image on dockerhub and it doesn't seem to be on https://docs.openshift.com/enterprise/3.0/using_images/s2i_images/python.html either.  When I try to use, e.g.,

```
 s2i build . centos/python-36-centos7 hello-world
```

The python36 image does not have pipenv support installed and, additionally, `python37-centos7` does not appear to exist.

Are the latest s2i images for python packaged? If so, how are they named?

**Comment by frenzymadness** [comment]
Hello.

- I am able to find Centos 7 with Python 3.6 on docker hub: https://hub.docker.com/r/centos/python-36-centos7
- If you wanna use Pipenv, you have to enable it via environment variable during a build of your image:
```
$ s2i build -e ENABLE_PIPENV=true . centos/python-36-centos7 hello-world
$ docker run --rm -it hello-world /bin/bash
(app-root) pipenv --version
pipenv, version 2018.11.26
```
You can also use `.s2i/environment` file for that.
- Centos image with Python 3.7 is not available simply because Python 3.7 RPM does not exist for Centos. Python 3.7 is currently available only on Fedora.

But you are right that readme files seem to be kinda outdated on Docker hub, we should investigate it more.

Can I help you more?

**Comment by jtratner** [comment]
@frenzymadness - Oh man I just tried it again and realized that it worked.  I'm so sorry to bother you.

I think what ended up happening to me initially is that I was running this in a local repo with:

```
s2i build . centos/python-36-centos7
```

without having committed the `.s2i` directory.

Then I thought "Oh it must be a wrong version deployed", built the whole image locally, didn't work again, found out about the `--copy` command and forgot to retest that on the published stuff.

Again, sorry to bother you!

That said - looks like docs on openshift are a bit out of date.

**Comment by frenzymadness** [comment]
No worries, I am always happy to help.

I've created a new issue https://github.com/sclorg/s2i-python-container/issues/324 to fix the documentation problem.
