### ISSUE TITLE
Can't find images with python 3.7 and 3.8 on docker-hub

### ISSUE THREAD

**Issue by leogout** [sclorg/s2i-python-container#376]
Hello, I can't find the susmentionned images on docker-hub: https://hub.docker.com/search?q=centos%2Fpython-3&type=image

Do you plan on building and pushing them yourself or is it expected that I do that on my local computer?  
Either way is fine for me but I was wondering why the 3.6, 3.5 and 3.4 were already online and not the other two. Are they not ready yet? Or maybe I am looking in the wrong place...

Thanks for this project, it is a huge help!

**Comment by frenzymadness** [comment]
Hello.

Python 3.7 is not and won't be available in RHEL and Centos so this version of Python is available only for Fedora.
Python 3.8 is available for Fedora 32 (still in beta and not yet released in the registry), RHEL 8 (as a module), RHEL 7 (as a software collection) and the same for Centos clones. But, Python 3.8 container images are still work in progress because Python 3.8 module and software collection are not finally released. We are working on them and we will release them as soon as possible.

By the way, could you tell us on which project are you using these images? We are interested in who are our customers.

Let me know if I can help you more.

**Comment by leogout** [comment]
Oh okay I see, I'll look into those thanks, I don't know the diff between Centos and Fedora 32 but I think it'll do for my UCs.  

Abour my usages, I have two main needs:  
- Running Flask applications in an s2i container thanks to gunicorn or uwsgi, though it wat tedious to install uwsgi from pip as it had to compile the C source code which is quite time consuming on smaller configs (~10 minutes on my low resources builder)
- Running django applications in an s2i container through the same process

Gunicorn doesn't handle the "serving static assets" part out of the box like uwsgi does, so I also had to add another dependency which is [whitenoise](http://whitenoise.evans.io/en/stable/index.html).
Usually I would use NGINX or something similar to serve those static assets as it is done in https://github.com/tiangolo/uwsgi-nginx-flask-docker but I don't have the skills to extend your dockerfiles and add an NGINX layer so I'll go with whitenoise for now.

If you have any other questions feel free to contact me here.
