### ISSUE TITLE
2.7 image vulnerable to CVE-2020-26116

### ISSUE THREAD

**Issue by ysangkok** [sclorg/s2i-python-container#405]
Even though 2.7 is out of support, Red Hat has patched to fix this httplib exploit. Would be nice to have it patched here too: https://access.redhat.com/errata/RHSA-2020:4273

**Comment by frenzymadness** [comment]
You are right. Python 2.7 is EOL but Red Hat still supports it. This means that when the fixes land in modules/collections in RHEL, they will be automatically included in the upcoming release of our containers based on RHEL.

I can take a look at a specific version of RHEL/module/collection and their combinations if you want. Otherwise, it's just matter of time.
