### ISSUE TITLE
ubi7/python-38 uses new django-ex -> failing test

### ISSUE THREAD

**Issue by lukaszachy** [sclorg/s2i-python-container#437]
When test suite is ran for `rh-python38-container`:
```
[FAILED] for  test_from_dockerfile
...
django.core.exceptions.ImproperlyConfigured: SQLite 3.8.3 or later is required (found 3.7.17).
```

**Comment by frenzymadness** [comment]
The problem is [here](https://github.com/sclorg/s2i-python-container/blob/master/3.8/test/run#L222) When the test runs for an image without `rhel7` or `ubi7` in the image name, it does not detect that it should use the older Django example.

We have to find a better way how to identify RHEL 7 from something else than the image name.
