### ISSUE TITLE
Python 3.9+ for Centos 7 docker images

### ISSUE THREAD

**Issue by tanvn** [sclorg/s2i-python-container#586]
Sorry, it seems that docker images for Python 3.9+ based on Centos 7 are not available.
May I know the reason why?

**Comment by frenzymadness** [comment]
Hello.

The reason is that Python 3.9 has never been released as a software collection for RHEL 7 / Centos 7. The latest Python version available there is 3.8, see: https://access.redhat.com/support/policy/updates/rhscl-rhel7

RHEL 7 / Centos 7 are close to their EOL so it makes sense to switch to RHEL 8 or 9. Python 3.9 is an alternative Python version in RHEL 8 with 3 years of support but it is the main Python version in RHEL 9 which means 10 years of support. If you need 3.9, the best is to use RHEL 9.

Does that answer your question? Is there anything else I can help you with?

**Comment by tanvn** [comment]
@frenzymadness 
Hi, thank you so much for your reply.
For some reason, I would like to run Python 3.9+ on Centos 7 if possible.
Do you know whether it is possible to add some modifications in the [Dockerfile](https://github.com/sclorg/s2i-python-container/blob/master/3.8/Dockerfile.centos7) to create a Docker image for Python 3.9?

**Comment by frenzymadness** [comment]
I'm afraid it won't be easy and the result is uncertain. The only way I see is to compile your own Python 3.9 from sources on Centos 7 but the main question here is whether there are new enough compiles and other stuff. The process of compilation is not that complicated and it's described here for example https://www.inmotionhosting.com/support/server/linux/install-python-3-9-centos-7/ or https://phoenixnap.com/kb/how-to-install-python-3-centos-7

The newer Python you use the lower os the probability that it will be compilable on Centos 7.

Doing so in a Dockerfile might lead to a huge container image because the compilation of Python requires a lot of header files and additional packages.

**Comment by tanvn** [comment]
@frenzymadness 
Thank you for your kind support!
I understood and managed to build a docker image for Python 3.9 based on Centos 7.9.

> Doing so in a Dockerfile might lead to a huge container image because the compilation of Python requires a lot of header files and additional packages.

You are correct, the size of the docker image is quite huge and several  extra packages are required.
Let me close this issue as to me, it has been resolved, thank you again!
